spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bdb
    username: budgdb
    password: 8gx$j(WCV
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
